sudo: required
services:
  - docker

before_install:
  - docker build -t iamhkisn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iamhkisn/react-test npm run test -- --coverage

after_success:
  - docker build -t iamhkisn/multi-client ./client
  - docker build -t iamhkisn/multi-nginx ./nginx
  - docker build -t iamhkisn/multi-server ./server
  - docker build -t iamhkisn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push iamhkisn/multi-client
  - docker push iamhkisn/multi-nginx
  - docker push iamhkisn/multi-server
  - docker push iamhkisn/multi-worker